In [1]:
pwd

'F:\\Education\\DS_Roadmap\\ml'

In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.read_csv("F:/Education/DS_Roadmap/ml/1_linear_reg/homeprices.csv")

In [4]:
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
reg = LinearRegression()

In [9]:
reg.fit(df[["area"]].values, df.price)

LinearRegression()

In [10]:
reg.predict([[5000]])

array([859554.79452055])

In [11]:
reg.coef_

array([135.78767123])

In [12]:
reg.intercept_

180616.43835616432

In [13]:
import pickle

In [14]:
with open("model_pickle", "wb") as f:
    pickle.dump(reg,f)

In [15]:
with open("model_pickle", "rb") as f:
    mp = pickle.load(f)

In [16]:
mp.predict([[5000]])

array([859554.79452055])

In [18]:
import joblib

In [19]:
joblib.dump(reg, "model_joblib")

['model_joblib']

In [20]:
mj = joblib.load("model_joblib")

In [21]:
mj.predict([[5000]])

array([859554.79452055])